version: "3.8"
services:
  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"

  server:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./.env:/app/.env
    depends_on:
      - "mongo"
